In [5]:
import pandas as pd
import numpy as np

data=pd.read_csv("C:/Users/REC/Downloads/transactions.csv")

In [6]:
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   1000 non-null   object
 1   Timestamp        1000 non-null   object
 2   Sender Name      1000 non-null   object
 3   Sender UPI ID    1000 non-null   object
 4   Receiver Name    1000 non-null   object
 5   Receiver UPI ID  1000 non-null   object
 6   Amount (INR)     1000 non-null   float64
 7   Status           1000 non-null   object
dtypes: float64(1), object(7)
memory usage: 62.6+ KB

In [7]:
data.tail()

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
995,843d87b5-902e-4336-9438-aa76d74e13e4,2024-07-03 23:15:06,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,SUCCESS
996,2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,2024-06-15 15:42:57,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,FAILED
997,7c38e684-5968-432e-8acb-5bbe0f718fad,2024-06-18 17:27:37,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,FAILED
998,27624b55-fd6d-45ce-bbc5-0c2958d48865,2024-06-05 21:57:36,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,FAILED
999,b792bf64-2047-4435-aac1-27ee95b134d6,2024-06-21 15:52:40,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,SUCCESS

In [8]:
data.describe()

       Amount (INR)
count   1000.000000
mean    4999.022930
std     2873.484534
min       28.520000
25%     2521.620000
50%     4951.435000
75%     7315.835000
max     9993.060000

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   1000 non-null   object
 1   Timestamp        1000 non-null   object
 2   Sender Name      1000 non-null   object
 3   Sender UPI ID    1000 non-null   object
 4   Receiver Name    1000 non-null   object
 5   Receiver UPI ID  1000 non-null   object
 6   Amount (INR)     1000 non-null   float64
 7   Status           1000 non-null   object
dtypes: float64(1), object(7)
memory usage: 62.6+ KB

In [10]:
data.isnull().sum()

Transaction ID     0
Timestamp          0
Sender Name        0
Sender UPI ID      0
Receiver Name      0
Receiver UPI ID    0
Amount (INR)       0
Status             0
dtype: int64

In [11]:
data.duplicated().sum()

0

In [12]:
data['Timestamp'] = pd.to_datetime(data['Timestamp'])
data.dtypes

Transaction ID             object
Timestamp          datetime64[ns]
Sender Name                object
Sender UPI ID              object
Receiver Name              object
Receiver UPI ID            object
Amount (INR)              float64
Status                     object
dtype: object

In [13]:
#total
data['Amount (INR)'].sum()

4999022.93

In [14]:
#average
data['Amount (INR)'].mean()

4999.02293

In [15]:
data['Status'].value_counts()

SUCCESS    502
FAILED     498
Name: Status, dtype: int64

In [16]:
data['Sender Name'].value_counts().head(10)

Prerak Lanka         2
Aayush Bakshi        2
Ivan Ramesh          2
Tiya Mall            1
Fateh Swaminathan    1
Kiaan Bhagat         1
Pranay Chaudry       1
Mishti Kakar         1
Shalv Dhawan         1
Pihu Gara            1
Name: Sender Name, dtype: int64

In [17]:
data['Status'].value_counts(normalize=True) * 100

SUCCESS    50.2
FAILED     49.8
Name: Status, dtype: float64